### ISSUE TITLE
请问training time window参数怎么修改？

### ISSUE THREAD

**Issue by lcyCQUPT** [Carkham/FLHetBench#1]
![图片1](https://github.com/user-attachments/assets/2aaa680c-da5e-4b13-944d-4ee5c6ea6c71)
训练时模型训练一直失败，提示 training time window is too short to train!

**Comment by Carkham** [comment]
hi你好，出现这个说明在仿真环境里你的模型下载，训练，上传的总时间超过了ddl这个参数。这可能和你的模型大小以及ddl设置有关。

解决这个问题有两个思路，1) 如果你想复现论文中的设备异质性和状态异质性的环境，你可以将model_size设为vit base对应的值，并将ddl设为120。2) 如果你想在自己的模型上跑，你可以根据模型的大小，增大ddl参数，使得足够多的client能够任务

**Comment by lcyCQUPT** [comment]
> hi你好，出现这个说明在仿真环境里你的模型下载，训练，上传的总时间超过了ddl这个参数。这可能和你的模型大小以及ddl设置有关。
> 
> 解决这个问题有两个思路，1) 如果你想复现论文中的设备异质性和状态异质性的环境，你可以将model_size设为vit base对应的值，并将ddl设为120。2) 如果你想在自己的模型上跑，你可以根据模型的大小，增大ddl参数，使得足够多的client能够任务

你好，我将ddl设置为120后还是出现同样的“training time window is too short to train!”问题，我尝试将ddl设置为300，运行时出现以下异常：
![截图_20241109150403](https://github.com/user-attachments/assets/eee63a68-7367-4b44-a7a0-129d65be4a93)

运行命令：python main.py --config configs/default.cfg --aggregation_strategy deadline --device_path cached_sample_data/device/case1.json --state_path cached_sample_data/state/case1.json --dataset_name openImg --deadline 300
数据集和模型是Readme文档中给的链接下载的openImg.npy和Vit-B_16.npz

**Comment by Carkham** [comment]
> > hi你好，出现这个说明在仿真环境里你的模型下载，训练，上传的总时间超过了ddl这个参数。这可能和你的模型大小以及ddl设置有关。
> > 解决这个问题有两个思路，1) 如果你想复现论文中的设备异质性和状态异质性的环境，你可以将model_size设为vit base对应的值，并将ddl设为120。2) 如果你想在自己的模型上跑，你可以根据模型的大小，增大ddl参数，使得足够多的client能够任务
> 
> 你好，我将ddl设置为120后还是出现同样的“training time window is too short to train!”问题，我尝试将ddl设置为300，运行时出现以下异常： ![截图_20241109150403](https://private-user-images.githubusercontent.com/180904985/384584999-eee63a68-7367-4b44-a7a0-129d65be4a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDE1ODgsIm5iZiI6MTczMTE0MTI4OCwicGF0aCI6Ii8xODA5MDQ5ODUvMzg0NTg0OTk5LWVlZTYzYTY4LTczNjctNGI0NC1hN2EwLTEyOWQ2NWJlNGE5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwODM0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzFhZGI4ZWNlNTZjMDAxYTRkOGNjY2UxMWNmOGU1ZjdkYzBiNWJiY2RjMDYxYmMyN2ZjZDRmMWQ0YmRkMGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JxEHmmaC1R_6rZ-9ptw-rlvF91cCQ30p6vd9iQz3X3s)
> 
> 运行命令：python main.py --config configs/default.cfg --aggregation_strategy deadline --device_path cached_sample_data/device/case1.json --state_path cached_sample_data/state/case1.json --dataset_name openImg --deadline 300 数据集和模型是Readme文档中给的链接下载的openImg.npy和Vit-B_16.npz

图中是正常现象，cached_sample_data/state/case1.json这个文件里的是最极端的状态异质性，因此会有大量时间无充足的可用设备。你可以先将其改为cached_sample_data/state/case4.json，试一下minor的状态异质性。

**Comment by lcyCQUPT** [comment]
> > > hi你好，出现这个说明在仿真环境里你的模型下载，训练，上传的总时间超过了ddl这个参数。这可能和你的模型大小以及ddl设置有关。
> > > 解决这个问题有两个思路，1) 如果你想复现论文中的设备异质性和状态异质性的环境，你可以将model_size设为vit base对应的值，并将ddl设为120。2) 如果你想在自己的模型上跑，你可以根据模型的大小，增大ddl参数，使得足够多的client能够任务
> > 
> > 
> > 你好，我将ddl设置为120后还是出现同样的“training time window is too short to train!”问题，我尝试将ddl设置为300，运行时出现以下异常： ![截图_20241109150403](https://private-user-images.githubusercontent.com/180904985/384584999-eee63a68-7367-4b44-a7a0-129d65be4a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDE1ODgsIm5iZiI6MTczMTE0MTI4OCwicGF0aCI6Ii8xODA5MDQ5ODUvMzg0NTg0OTk5LWVlZTYzYTY4LTczNjctNGI0NC1hN2EwLTEyOWQ2NWJlNGE5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwODM0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzFhZGI4ZWNlNTZjMDAxYTRkOGNjY2UxMWNmOGU1ZjdkYzBiNWJiY2RjMDYxYmMyN2ZjZDRmMWQ0YmRkMGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JxEHmmaC1R_6rZ-9ptw-rlvF91cCQ30p6vd9iQz3X3s)
> > 运行命令：python main.py --config configs/default.cfg --aggregation_strategy deadline --device_path cached_sample_data/device/case1.json --state_path cached_sample_data/state/case1.json --dataset_name openImg --deadline 300 数据集和模型是Readme文档中给的链接下载的openImg.npy和Vit-B_16.npz
> 
> 图中是正常现象，cached_sample_data/state/case1.json这个文件里的是最极端的状态异质性，因此会有大量时间无充足的可用设备。你可以先将其改为cached_sample_data/state/case4.json，试一下minor的状态异质性。

我尝试了case4.json设置，在300的ddl设定下本地模型基本能成功上传参数，可是average acc一直是-1.0 这是什么原因呢？
![20241109172533](https://github.com/user-attachments/assets/5faeebd3-0fac-4f67-b48d-7634d0bd7d9a)

感谢您的耐心解答

**Comment by Carkham** [comment]
> > > > hi你好，出现这个说明在仿真环境里你的模型下载，训练，上传的总时间超过了ddl这个参数。这可能和你的模型大小以及ddl设置有关。
> > > > 解决这个问题有两个思路，1) 如果你想复现论文中的设备异质性和状态异质性的环境，你可以将model_size设为vit base对应的值，并将ddl设为120。2) 如果你想在自己的模型上跑，你可以根据模型的大小，增大ddl参数，使得足够多的client能够任务
> > > 
> > > 
> > > 你好，我将ddl设置为120后还是出现同样的“training time window is too short to train!”问题，我尝试将ddl设置为300，运行时出现以下异常： ![截图_20241109150403](https://private-user-images.githubusercontent.com/180904985/384584999-eee63a68-7367-4b44-a7a0-129d65be4a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDE1ODgsIm5iZiI6MTczMTE0MTI4OCwicGF0aCI6Ii8xODA5MDQ5ODUvMzg0NTg0OTk5LWVlZTYzYTY4LTczNjctNGI0NC1hN2EwLTEyOWQ2NWJlNGE5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwODM0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzFhZGI4ZWNlNTZjMDAxYTRkOGNjY2UxMWNmOGU1ZjdkYzBiNWJiY2RjMDYxYmMyN2ZjZDRmMWQ0YmRkMGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JxEHmmaC1R_6rZ-9ptw-rlvF91cCQ30p6vd9iQz3X3s)
> > > 运行命令：python main.py --config configs/default.cfg --aggregation_strategy deadline --device_path cached_sample_data/device/case1.json --state_path cached_sample_data/state/case1.json --dataset_name openImg --deadline 300 数据集和模型是Readme文档中给的链接下载的openImg.npy和Vit-B_16.npz
> > 
> > 
> > 图中是正常现象，cached_sample_data/state/case1.json这个文件里的是最极端的状态异质性，因此会有大量时间无充足的可用设备。你可以先将其改为cached_sample_data/state/case4.json，试一下minor的状态异质性。
> 
> 我尝试了case4.json设置，在300的ddl设定下本地模型基本能成功上传参数，可是average acc一直是-1.0 这是什么原因呢？ ![20241109172533](https://private-user-images.githubusercontent.com/180904985/384592833-5faeebd3-0fac-4f67-b48d-7634d0bd7d9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNTgyMjcsIm5iZiI6MTczMTE1NzkyNywicGF0aCI6Ii8xODA5MDQ5ODUvMzg0NTkyODMzLTVmYWVlYmQzLTBmYWMtNGY2Ny1iNDhkLTc2MzRkMGJkN2Q5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxMzEyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWRiYzQxMGIwODNlZjQzZDc0NzNjMjc4MzA5MDdjMjdhNjVkZDUxNTY0ZmI4NDU3ZGMwMTczNmE5NWIzOTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3zBjGzrgz9OcPhqG6eJRSiGe5VjInxNaPbawbE4AB_A)
> 
> 感谢您的耐心解答

这个是因为在代码里，为了简化每一轮通信的训练，没有去计算average_acc，而是将它设为-1（因为每一轮都去做测试的话，训练很慢）。如果你想看训练时的准确率，你可以在mimic_model.py中计算loss的地方自己算一下然后回传给client.py中调用的地方。如果你想看测试/验证集的准确率，你可以在--config所指定的配置文件（你的命令是default.cfg）中设置eval_every，来实现每经过多少轮通信后计算测试/验证集的准确率。

**Comment by lcyCQUPT** [comment]
明白了，感谢您的分享和耐心解答
